substitutions:
  name: "sensor-5n-cr-v1"
  friendly_name: "Sensor 5 Niveis-CR-v1"
  room: ""
  device_description: "Sensor de 5 Niveis com relê"
  project_name: "Automakaza.Sensor 5 Niveis CR-v1"
  project_version: "1.05"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev

# Ativa log
logger:
  level: INFO

# Ativa Home Assistant API
api:

ota:

wifi:
  ap: {}

# ativa um hotspot (captive portal) caso a conexão wifi falhe
captive_portal:
